name: ncnn_yolox_flutter
description: This is a plugin to run YOLOX on ncnn.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  plugin:
    platforms:
      android:
        package: dev.kingu.ncnn_yolox_flutter
        pluginClass: NcnnYoloxFlutterPlugin
      ios:
        pluginClass: NcnnYoloxFlutterPlugin
